name: 🛠️ Build

vars:
  icon_file: res/rubisco.ico
  group: The C++ Plus Project
  copyright: Copyright (C) 2024 The C++ Plus Project

steps:
  - mkdir: dist

  - name: 🛠️ Build wheel distribution
    run:
      [
        "python",
        "-m",
        "build",
        "--wheel",
        "--outdir=dist",
        "--verbose",
      ]
