name: 🛠️ Build cppp-srcpkg

steps:
  - copy: cppp_srcpkg
    to: .bindir/cppp_srcpkg
    excludes: ["__pycache__", "*.pyc"]

  - workflow: .rubisco/po.yaml

  - name: 🛠️ Build RuBP.
    type: rubp-pack
